data:
    dataset: kitti
    train_split: assets/train.csv
    valid_split: assets/val.csv
training:
    train_iters: 85000
    batch_size: 2
    val_interval: 500
    print_interval: 25
    optimizer:
        lr: 1.0e-4
    l_rate: 1.0e-4
    l_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    resume:
    visdom: False
    device: 'cpu'
seed: 1103